### ISSUE TITLE
IUnitOfWork is a part of domain?

### ISSUE THREAD

**Issue by dario-l** [kgrzybek/modular-monolith-with-ddd#11]
Why [IUnitOfWork](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/BuildingBlocks/Domain/IUnitOfWork.cs) is a part of domain?

It is used only in Application parts and implementation is in Infrastructure.

**Comment by kgrzybek** [comment]
In my opinion it doesn't matter where it is used, it matters what concept represents.

Some people place this interface in Domain (for example [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/SeedWork/IUnitOfWork.cs)), some don't.

Quote from [Martin's Fowler catalogue](https://martinfowler.com/eaaCatalog/unitOfWork.html):

> Maintains a list of objects affected by a business transaction and coordinates the writing out of changes and the resolution of concurrency problems.

In my opinion it lives on boundary between Domain (it concerns about business transaction) and Infrastructure (using database transaction). For me it is closer to Domain but I think placing it in Infrastructure is OK too.
