### ISSUE TITLE
Duplicated items on *.Modules.Application

### ISSUE THREAD

**Issue by denizkanmaz** [kgrzybek/modular-monolith-with-ddd#12]
Hi Kamil,

I see that there are some items located in each module and completely the same except their namespaces. For instance, CommandBase, ICommand, IQuery etc.

I would like to ask about this approach. What could be wrong if we put them in a common library (for instance "CompanyName.MyMeetings.Modules.Common.Application") to avoid code duplication?

Thank you.

**Comment by kgrzybek** [comment]
Hi @denizkanmaz 

This duplication was created purposely to avoid executing Commands / Queries which particular Module doesn't handle. In other words - interface of each module is very strict and you will receive compilation error if you would try to execute Command/Query which is not part of Contract of this module.

Example:

```csharp
await _userAccessModule.ExecuteCommandAsync(new RegisterNewUserCommand(request.Login, request.Password,
    request.Email, request.FirstName, request.LastName)); // OK, this command is part of User Access Module

await _userAccessModule.ExecuteCommandAsync(new ProposeMeetingGroupCommand(
    "name", "description", "city", "country")); // Compile error, this command is part of Meeting Module
```
