### ISSUE TITLE
Wrong InboxMessages table pointed in UserAccess module

### ISSUE THREAD

**Issue by JacekSmi** [kgrzybek/modular-monolith-with-ddd#128]
Hey 👋 @kgrzybek 
Just a quick question.
For me it looks like you are getting data from wrong table it should be [users].[InboxMessages] ?
https://github.com/kgrzybek/modular-monolith-with-ddd/blob/3c2d67229e56a3dec19611abd260d2526f16893d/src/Modules/UserAccess/Infrastructure/Configuration/Processing/Inbox/ProcessInboxCommandHandler.cs#L32

Or I missing something ?

**Comment by kgrzybek** [comment]
Hey @JacekSmi, thanks! You were right - it was a bug. I fixed it.
