### ISSUE TITLE
Using RabbitMQ insted of in-memory bus and execute asynchronous command 

### ISSUE THREAD

**Issue by mehdihadeli** [kgrzybek/modular-monolith-with-ddd#13]
Hi,
@kgrzybek Thanks for your great project. 
I have a question in my mind, why you don't use RabbitMQ for your message broker insted of in-memory command bus and also use of RabbitMQ for handling asynchronous command insted of hangfire?

**Comment by kgrzybek** [comment]
You can use RabbitMQ for both cases but you have to keep in mind that RabbitMQ is another **executable** component (like database) so your overall solution complexity will **increase**. Another executable means another communication through **network**, configuration, deployment, maintainance etc. 

So, if you don't have **architectural drivers** to use separate message broker you should take much simpler solution. In Memory Event Bus and Quartz background jobs processor are examples of these kind of solutions. RabbitMQ is powerful but you need to ask yourself if you really need it to solve your **business problems**.

**Comment by mehdihadeli** [comment]
> You can use RabbitMQ for both cases but you have to keep in mind that RabbitMQ is another **executable** component (like database) so your overall solution complexity will **increase**. Another executable means another communication through **network**, configuration, deployment, maintainance etc.
> 
> So, if you don't have **architectural drivers** to use separate message broker you should take much simpler solution. In Memory Event Bus and Quartz background jobs processor are examples of these kind of solutions. RabbitMQ is powerful but you need to ask yourself if you really need it to solve your **business problems**.

@kgrzybek Yes you right, depending on the project scale and our purpose we can use the appropriate solutions.

**Comment by paulvanbladel** [comment]
It might be interesting to understanding why in a modular monolith replacing the in memory bus is useless.
In the microservice world you typically will update and redeploy an individual service while the rest of the app stays online. In that scenario it's important to persist the integration events in a physical queue rather than in memory.
That's, at least in my understanding, not applicable in a modular monolith since everything is always deployed as a whole.
