### ISSUE TITLE
Database connection string issue.

### ISSUE THREAD

**Issue by majedur** [kgrzybek/modular-monolith-with-ddd#133]
Hi @kgrzybek ,

Thanks for your nice work. 
I have set up connection string in the appsettings.json file but I am experiencing an exception. I will be grateful if someone help me with this. Thanks in advanced. 
![Capture](https://user-images.githubusercontent.com/6143163/98116709-c45db700-1efc-11eb-8dd3-f7244115a4c5.PNG)
![Capture](https://user-images.githubusercontent.com/6143163/98116886-0d157000-1efd-11eb-94ff-ea9a42ad8f3d.PNG)

**Comment by beirinha** [comment]
Hello @majedur, I thinkk the structure of your json it`s incorrect.

Try this:
![image](https://user-images.githubusercontent.com/12887713/98124669-4238a880-1e92-11eb-91e8-d408506e9472.png)

**Comment by majedur** [comment]
Hi Beirinha,
It's working. Thanks for your help.
