### ISSUE TITLE
Added validation of aggregate existence when calling command

### ISSUE THREAD

**Issue by KmlPro** [kgrzybek/modular-monolith-with-ddd#134]
Hi,

in command validators I do not see any validation checking the existence of a given aggregate.

could you add such an example?

**Comment by dario-l** [comment]
There is. Checkout the [UserLoginMustBeUniqueRule](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/Modules/UserAccess/Domain/UserRegistrations/Rules/UserLoginMustBeUniqueRule.cs).

**Comment by KmlPro** [comment]
Thanks ! :)
