### ISSUE TITLE
Migration with efcore

### ISSUE THREAD

**Issue by tinquen12** [kgrzybek/modular-monolith-with-ddd#157]
Hello ! 

This repository is such an amazing ressource, so first of all thank you so much for that work. 😄 

I try to migrate an existing project to this architecture and I'm having some trouble to make the efcore migration work.

In fact, when I run `Add-Migration Initial` on Infrastructure project of the module I want to create the migration for (with startup project the API project) , I got the following error : 

`No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.`

I'm a bit lost why that is happening. Anybody have any clue on how to resolve that ?

Thank you very much !

**Comment by Serfin** [comment]
Does this project even use EF Core migrations? The only usage of EFCore I found is the ORM write model (Dapper is used for reading data) As far as I know project is using DbUp and SSDT. Someone please correct me if I'm wrong.

https://github.com/kgrzybek/modular-monolith-with-ddd#316-database-change-management

**Comment by tinquen12** [comment]
Thank you very much for your response.

Yes you are right, the project, at the moment doesn't use EF Core migrations. And you are also right on the fact that Efcore is used only on the Command part and Dapper on the Query side.

But I try to make my own implementation on an existing project in a team that heavily rely on Efcore. My question was more "Is it possible to use Efcore migration on that kind of project ?".

The problem I have is because of the project structure and I was asking some help to understand how to implement it. 😃

**Comment by Serfin** [comment]
Are you sure that those extra constructors are needed? I am pretty sure that EF is taking the parameterless constructor and does not pass DbContextOptions model to base constructor which is required by EF. I was able to reproduce your error after I added the second constructor to my Context file.

**Comment by Serfin** [comment]
Ok, I was struggling with same error for some time and I found that this error is related to way we register DbContext in Autofac

This causes some troubles with later DbContextOptions injection (but during debug everything looks fine, instance is created)
```cs

builder.Register(c =>
    {
        var dbContextOptionsBuilder = new DbContextOptionsBuilder<AdministrationContext>();
        dbContextOptionsBuilder.UseSqlServer(_connectionString);
    
        return new AdministrationContext(dbContextOptionsBuilder.Options);
    })
    .AsSelf()
    .InstancePerLifetimeScope();
```
If you swap your registration back to native IoC in ConfigureServices everything works fine and migration is properly created.
```cs

services.AddDbContext<AdministrationContext>(x => x.UseSqlServer(
    Configuration.GetConnectionString("sqlServer"), x =>
    {
        x.CommandTimeout(30);
        x.EnableRetryOnFailure(3);
    }));
```

**Comment by kgrzybek** [comment]
Hi @tinquen12 

Firstly, thanks for your kind words! I am glad that is useful for you.

As you noticed this project doesn't use EF migrations. I tried EF migrations a long time ago but I didn't like it and I don't track the progress of that library.

Here and in my production systems, I use [DbUp](https://dbup.github.io/) library so I can't help you with EF migrations. However, if you want to read about my insights about the database change management approach check my 2 related posts:
https://www.kamilgrzybek.com/database/database-change-management/
https://www.kamilgrzybek.com/database/using-database-project-and-dbup-for-database-management/

**Comment by tinquen12** [comment]
Hello,

No worries. I could not find some time to work on that subject. When I will have some achievement I will post her 😄

**Comment by tinquen12** [comment]
I had some achievements on that topic. I implemented a ContextFactory and now its working as expected


```cs

public class AdministrationContextFactory : IDesignTimeDbContextFactory<AdministrationContext>
    {
        private ILogger _logger { get; set; }
        public AdministrationContextFactory(ILogger logger)
        {
            _logger = logger;
        }

        public AdministrationContextFactory() { }
        public AdministrationContext CreateDbContext(string[] args)
        {
            // TODO : Change that to get it from the api project 
            string connectionString = "Server=(localdb)\\mssqllocaldb;Database=DriverConfigurationv2;Trusted_Connection=True;";
            var loggerFactory = new SerilogLoggerFactory(_logger);

            return DbContextHelper.CreateContext<AdministrationContext>(connectionString, loggerFactory);
        }
    }
```

😃
