### ISSUE TITLE
Consider Blazor as SPA framework

### ISSUE THREAD

**Issue by isaacbromberg** [kgrzybek/modular-monolith-with-ddd#16]
It has preview status at the moment but quick development form experimental to preview makes me sure that it is good option if someone doesn't enjoy JS (Blazor apps are in c#) . Hi-speed of web assembly is nice side effect.

https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor

**Comment by teqow** [comment]
Why do You think full stack .net developers must be focused on blazor? I work as full stack .net developer and I dont see necessary choose blazor, for me we have better choices, like react etc. Why? Because for me mix c# code with js/html etc is bad idea to build spa applications.

**Comment by isaacbromberg** [comment]
@teqow, as a response I edited my post.

**Comment by kgrzybek** [comment]
Hej @isaacbromberg 

I consider Angular because I have the most production experience with this SPA framework.

Unfortunately, I don't have time now to create a FrontEnd application for this repository. If anybody would like to create FrontEnd application in (Blazor/Angular/React/Vue) for this project it would be great

**Comment by 274188A** [comment]
I'm fairly new to token tech but I have tried to use Postman to send a POST with simply query strings to get an OAuth2 token (below).   

I think I'm missing something but is there an endpoint for doing Auth?

`https://localhost:5000?grant_type=password&username=testMember@mail.com&password=testMemberPass&client_id=ro.client&client_secret=secret`

I'm happy to help write up some steps as I'm probably the perfect person with low knowledge in this token world :-)

**Comment by szenadam** [comment]
@kgrzybek I think this issue should be closed and any further discussion moved to #59

**Comment by kgrzybek** [comment]
@szenadam I agree
