### ISSUE TITLE
Whole event storming file

### ISSUE THREAD

**Issue by mehdihadeli** [kgrzybek/modular-monolith-with-ddd#162]
Hi,
Is it possible to place a complete event storming file in your project or miro link?

**Comment by kgrzybek** [comment]
No problem @mehdihadeli - done! 

https://github.com/kgrzybek/modular-monolith-with-ddd/commit/39cf98e1a9b6832c0f7034814c6d7ec3dc211d9c

**Comment by mehdihadeli** [comment]
@kgrzybek Thanks for diagram :) 
Could you introduce me your studied reference for event storming?

**Comment by kgrzybek** [comment]
https://github.com/kgrzybek/modular-monolith-with-ddd#event-storming :)

**Comment by mehdihadeli** [comment]
@kgrzybek I read this section of your repository, but I need to study more resources for clarifying.
