### ISSUE TITLE
Missing application layer in module architecture tests

### ISSUE THREAD

**Issue by GregoireWulliamoz** [kgrzybek/modular-monolith-with-ddd#177]
First of all, I want to thank you for this huge masterpiece of knowledge that you all are building.

If I am not wrong, there is an issue in the module architecture tests. In the list of assemblies, the infrastructure layer is referenced two times. To fix that the module interface should be referenced instead.

`            List<Assembly> administrationAssemblies = new List<Assembly>
            {
                typeof(AdministrationModule).Assembly,
                typeof(MeetingGroupLocation).Assembly,
                typeof(AdministrationContext).Assembly
            };`

Should be

`            List<Assembly> administrationAssemblies = new List<Assembly>
            {
                typeof(IAdministrationModule).Assembly,
                typeof(MeetingGroupLocation).Assembly,
                typeof(AdministrationContext).Assembly
            };`

**Comment by kgrzybek** [comment]
Hi @GregoireWulliamoz ,

You are right, it was incorrect :)

Thank you for that contribution!
