### ISSUE TITLE
Architecture Decision Records?

### ISSUE THREAD

**Issue by jimmcslim** [kgrzybek/modular-monolith-with-ddd#19]
I wonder whether it would be good to add Architecture Decision Records (ADRs) https://adr.github.io/ into this project? They might be a little contrived, but it would good to see them added to this project in its role as an exemplar.

**Comment by kgrzybek** [comment]
Definitely a good idea and I thought about it recently. I will try to add entries to the most important decisions in the near future

**Comment by kgrzybek** [comment]
Hi @jimmcslim, I created Architecture Decisions Log and have added 16 ADRs. I think the most important decisions are described. I plan to keep this log up to date.

Log available here: https://github.com/kgrzybek/modular-monolith-with-ddd/tree/master/docs/architecture-decision-log
