### ISSUE TITLE
Async methods in domain service

### ISSUE THREAD

**Issue by sreejith-ms** [kgrzybek/modular-monolith-with-ddd#201]
The method `CountUsersWithLogin` in `IUsersCounter` is synchronous, how to make it `async`?

I have introduced `IsBrokenAsync` to resolve this and it will introduce `async` methods in the domain model.
This seems to be a bad idea after reading this [domain model purity](https://enterprisecraftsmanship.com/posts/domain-model-purity-lazy-loading/) article. Is this the reason behind the method `CountUsersWithLogin` created as synchronous?

Any thoughts on how to handle this?

**Comment by kgrzybek** [comment]
Hi @sreejith-ms 

We just need to live with it. I mean the ideal solution is to count users in the application layer and provide this count to the domain. But sometimes for performance reasons, this is not an optimal solution and then you can use method injection. I don't like async/await in Domain Model so I would rather stick with sync and change to async if a performance issue will appear.

**Comment by sreejith-ms** [comment]
Thanks @kgrzybek
