### ISSUE TITLE
Application layer design

### ISSUE THREAD

**Issue by michal880** [kgrzybek/modular-monolith-with-ddd#23]
Hi @kgrzybek , first of all, thanks for your work! 

I have been going thru the codebase and I have noticed an approach which slightly differs from my own, thus I wanted to ask some questions to better understand the drivers & reasoning behind it. 

In the application layer, there is a lot of dependencies, which I usually delegate to infrastructure layer.
For example - event bus related stuff, DI modules, logging, schedulers - basically everything that is not Command or CommandHandler. Sometimes it happens, that in CommandHandler you need something more. In that case, I usually go for the interface in the application layer implemented in the infrastructure layer. 

Speaking of modules, I noticed that in each module there are usually couple of autofac modules, e.g. MediatorModule, QuartzModule, DataAccessModule. What is the reason of that? 

Each .csproj has a reference to Microsoft.NETCore.App - would you consider switching that to .netstandard? I reference the platform at the top-level such as API (CompanyName.MyMeetings.API in this case). Benefit of that is that it allows my to easily switch the platform and has much less coupling for my application.

I want to make it clear that I'm not trying to say the only valid way to do something is "my & only righteous way". I'm more of looking for exchange of thoughts and maybe an improvement in common understanding.

If you think that something can be extracted to separate issue, please do so, I didn't want to spam you 😄

**Comment by kgrzybek** [comment]
Hi @michal880 

> In the application layer, there is a lot of dependencies, which I usually delegate to infrastructure layer.
> For example - event bus related stuff, DI modules, logging, schedulers - basically everything that is not Command or CommandHandler. Sometimes it happens, that in CommandHandler you need something more. In that case, I usually go for the interface in the application layer implemented in the infrastructure layer.

This is a good point. It was a decision because I treated the Application layer as an entry gate to module and application layer (like module host), so API could reference only this project. Recently, I changed my mind and decided to move the whole configuration to Infrastructure. The advantage is that the whole module architecture is cleaner. The disadvantage is that API needs references App and Infra now. 

> Speaking of modules, I noticed that in each module there are usually couple of autofac modules, e.g. MediatorModule, QuartzModule, DataAccessModule. What is the reason of that?

I like more granular Autofac modules, but I think is the matter of choice.

> Each .csproj has a reference to Microsoft.NETCore.App - would you consider switching that to .netstandard? I reference the platform at the top-level such as API (CompanyName.MyMeetings.API in this case). The benefit of that is that it allows me to easily switch the platform and has much less coupling for my application.

No, I have not considered it. I plan to migrate to .NET Core 3.1 first. After that I don't know if it would be possible.
