### ISSUE TITLE
Update to .NET 6.0 / 7.0?

### ISSUE THREAD

**Issue by JohanHeyvaert** [kgrzybek/modular-monolith-with-ddd#264]
This looks like a really great project! Thanks for sharing it, including the fantastic documentation and argumentation. ❤️ 

However the project seems a bit outdated now. I'm trying to update it myself but for the moment unsuccessful. Also an update of the Nuget packages is not really succeeding. Maybe it's a bit too late to still be able to update this project. 😨 

By any chance, are you thinking of an update yourself? 😀 

Or maybe someone else is able to do this and wants to add a pull request?

**Comment by AntosDev** [comment]
Thanks a lot for sharing this project @kgrzybek it is very helpful, but @JohanHeyvaert is right, is there any plan to update it to .net 6 at least?
You've already done a great job with this repo, let's not let time squash it away!

**Comment by jeffward01** [comment]
> Thanks a lot for sharing this project @kgrzybek it is very helpful, but @JohanHeyvaert is right, is there any plan to update it to .net 6 at least? You've already done a great job with this repo, let's not let time squash it away!

Im sure your perfectly competent at doing this yourself too 😄 , i'm sure @kgrzybek has been busy, and would absolutely appreciate your PR

C'mon - let's not let time squash it away!

**Comment by AlmarAubel** [comment]
Maybe update to .net8.0? ;)

**Comment by bistok** [comment]
there are a Pull Request from @AlmarAubel that updated to .net 7 , and I have a fork that I updated to .NET 8, in my repro you will see not only .net update, but packages update too.
https://github.com/bistok/modular-monolith-with-ddd/tree/upgrade-to-net7.0

**Comment by kgrzybek** [comment]
Guys, @AlmarAubel pr merged so we have 7.0 :)

I resume development of this repository and first step would be to upgrade libraries and then maybe upgrade to .NET 8.0 (I hope it will be easy)

**Comment by bistok** [comment]
@kgrzybek I have done the .NET  migration to 8 over @AlmarAubel changes and was not that easy because updated all the packages, was various days yesterday updated nuke that was the last bit that was failing, you can see my repository and the changes. maybe I can send the PR Directly to this repository

**Comment by kgrzybek** [comment]
@bistok Yes, please send PR directly to this repository so I will review it quickly :) 

I know there are some breaking changes in the nuke but I see you have handled them so everything should work but I will check it.

**Comment by bistok** [comment]
open PR #286 this will be a little bit more large to check in because the different bases, but thanks for the Review

**Comment by kgrzybek** [comment]
Project migrated to .NET 8.0 in #286
