### ISSUE TITLE
Remove Unused `using` Directives Following .NET 7/8 Update

### ISSUE THREAD

**Issue by AlmarAubel** [kgrzybek/modular-monolith-with-ddd#293]
After upgrading our project to .NET 7/8, we've observed a significant number of unused using directives across our codebase. This occurrence primarily stems from the introduction of global using statements in the newer .NET versions, rendering many of the existing using statements redundant.

Proposed Solution
To address this, I propose an automated cleanup of these unused using directives. Utilizing the code analysis and refactoring capabilities of Rider or Visual studio, we can efficiently identify and remove these redundancies. This action is expected to impact approximately 150 files.

Because of this impact it's maybe better if  you (@kgrzybek) you remove it your self so you won't have to review all the changed files manually.

**Comment by kgrzybek** [comment]
Done, more than 600 files changed (Rider refactor).
