### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by jreeter** [kgrzybek/modular-monolith-with-ddd#3]
Excuse the ignorance and unless I missed it in the docs, how does this system handle errors, particularly on the command side? It looks like most of controllers return ok(); 

Is this something to come?

**Comment by teqow** [comment]
> Each Command processing is decorated by 3 decorators: logging, validation and unit of work.

For domain logic you have for example FluentValidation -> Rules.

**Comment by kgrzybek** [comment]
There are 2 types of validation: Command data validation and business rules validation.

Command data validation is always executed using ``FluentValidation`` library by ``ValidationCommandHandlerDecorator`` and throws **InvalidCommandException**:

```csharp
internal class ValidationCommandHandlerDecorator<T> : ICommandHandler<T> where T:ICommand
{
    private readonly IList<IValidator<T>> _validators;
    private readonly ICommandHandler<T> _decorated;

    public ValidationCommandHandlerDecorator(
        IList<IValidator<T>> validators, 
        ICommandHandler<T> decorated)
    {
        this._validators = validators;
        _decorated = decorated;
    }

    public Task<Unit> Handle(T command, CancellationToken cancellationToken)
    {
        var errors = _validators
            .Select(v => v.Validate(command))
            .SelectMany(result => result.Errors)
            .Where(error => error != null)
            .ToList();

        if (errors.Any())
        {
            var errorBuilder = new StringBuilder();

            errorBuilder.AppendLine("Invalid command, reason: ");

            foreach (var error in errors)
            {
                errorBuilder.AppendLine(error.ErrorMessage);
            }

            throw new InvalidCommandException(errorBuilder.ToString(), null);
        }

        return _decorated.Handle(command, cancellationToken);
    }
}

public class AuthenticateCommandValidator : AbstractValidator<AuthenticateCommand>
{
    public AuthenticateCommandValidator()
    {
        this.RuleFor(x => x.Login).NotEmpty().WithMessage("Login cannot be empty");
        this.RuleFor(x => x.Password).NotEmpty().WithMessage("Password cannot be empty");
    }
}
```

Business rules validation is performed inside entities using ``CheckRule`` method and throws **BusinessRuleValidationException**:
```csharp
public void AddAttendee(MeetingGroup meetingGroup, MemberId attendeeId, int guestsNumber)
{
    this.CheckRule(new MeetingCannotBeChangedAfterStartRule(_term));

    this.CheckRule(new AttendeeCanBeAddedOnlyInRsvpTermRule(_rsvpTerm));
...
```

These exceptions are catched by "Problem Details" .NET Core middleware which maps exception to Problem Details class at ``Startup``:

```csharp
services.AddProblemDetails(x =>
{
    x.Map<InvalidCommandException>(ex => new InvalidCommandProblemDetails(ex));
    x.Map<BusinessRuleValidationException>(ex => new BusinessRuleValidationExceptionProblemDetails(ex));
});
```

More details here:
[https://www.kamilgrzybek.com/design/rest-api-data-validation/](https://www.kamilgrzybek.com/design/rest-api-data-validation/)

[https://www.kamilgrzybek.com/design/domain-model-validation/](https://www.kamilgrzybek.com/design/domain-model-validation/)

**Comment by slipdef** [comment]
Isn't exception is for exceptional cases only, not a general validation mechanism? Like violating business rule doesn't sound like an exceptional case, it's more an expected flow where user can make mistakes and we have to account for them using usual C# constructs.

**Comment by kgrzybek** [comment]
You can follow the approach with exceptions or use the "return object" approach. Both approaches are in my opinion good and which one you choose depends on various factors. 

I created ADR for this - [ADR 13 Protect business invariants using exceptions](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/docs/architecture-decision-log/0013-protect-business-invariants-using-exceptions.md)

**Comment by sm-g** [comment]
@kgrzybek I'm reading your https://www.kamilgrzybek.com/design/rest-api-data-validation/ and found that `title` in problem details reponse which your code generates is different from case to case, which violates the RFC7807 (https://tools.ietf.org/html/rfc7807#section-3.1). `Title` is just function of `type` for humans. Better place for messages for validators is `details` or even custom extensions (see examples in https://tools.ietf.org/html/rfc7807#section-3)

**Comment by kgrzybek** [comment]
Thanks @sm-g, I agree and created new issue for this - #40
