### ISSUE TITLE
Database migrations?

### ISSUE THREAD

**Issue by fodor99** [kgrzybek/modular-monolith-with-ddd#34]
popular for JAVA: https://flywaydb.org

**Comment by grexican** [comment]
@fodor99 this project is using a SQL DB project (.sqlproj). Migrations happen using a DB Schema comparison via DACPAC.

**Comment by kgrzybek** [comment]
@fodor99 

Database migrations have been implemented recently using DbUp library. See https://github.com/kgrzybek/modular-monolith-with-ddd/pull/107 and https://github.com/kgrzybek/modular-monolith-with-ddd#316-database-change-management
