### ISSUE TITLE
Rename MeetingsAutofacModule.cs to PaymentsAutofacModule.cs

### ISSUE THREAD

**Issue by DominiqueFonteyn** [kgrzybek/modular-monolith-with-ddd#37]
Hi,

It looks like there is a naming mistake with the file 
modular-monolith-with-ddd/src/API/CompanyName.MyMeetings.API/Modules/Payments/MeetingsAutofacModule.cs.
I believe it should be PaymentsAutofacModule.cs.

If I'm wrong, could you elaborate on why you named it this way?

Best regards
Dominique

**Comment by kgrzybek** [comment]
Thanks @DominiqueFonteyn, it was "copy-paste" mistake 😄  Fixed in b2ec0d9cb440d2a48d4687679ba0a1561b7597b1
