### ISSUE TITLE
Event Storming Policies

### ISSUE THREAD

**Issue by jgozner** [kgrzybek/modular-monolith-with-ddd#38]
Hey!

I just wanted to say thanks for such a great project. It's really helped me clear up questions that I've had around DDD. I just have one question regarding event storming and policies. Usually you would have the following flow in an event storming scenario.

<img width="781" alt="event-storming" src="https://user-images.githubusercontent.com/32521239/75221507-d88acb00-5756-11ea-97d9-038f2d32374f.png">

I'm trying to wrap my head around **Policies** and where to place the logic.

 When a domain event is fired you would have a Notification to wrap that event and a NotificationHandler in the Application layer to handle the event. Where would you place the policy logic? In the NotificationHandler?

**Comment by kgrzybek** [comment]
Thank you for question @jgozner !

Firstly, let me quote nice explanation what policy is (from https://developer.ibm.com/technologies/java/tutorials/reactive-in-practice-1/):

> Reactions (also known as policies) help to model system-initiated commands in response to events happening. For instance, we may want to initiate a command when something else happens. It’s this ‘when, then‘ notation that makes reactions very handy to use in modelling workshops. By convention, reactions are represented using lavender sticky notes. We can insert them between an event or a command, which makes it easy to model policies, with multiple commands being triggered from one event, or to attach the lavender sticky directly to a command, where a policy only has a single command associated with it.

Answering your question, in my opinion: policy logic should be placed in Event Handler when it is simple. When the logic is complex, this logic should be placed in your Domain (for example in Domain Service) and Event Handler should only delegate and coordinate this process. 

There is one example of this very easy logic policy in this project:
- Given Attendee is added to Meeting 
- When Fee is not empty 
- Then create a Meeting Payment

```csharp
internal class MeetingAttendeeAddedIntegrationEventHandler : INotificationHandler<MeetingAttendeeAddedIntegrationEvent>
{
    private readonly ICommandsScheduler _commandsScheduler;

    internal MeetingAttendeeAddedIntegrationEventHandler(ICommandsScheduler commandsScheduler)
    {
        _commandsScheduler = commandsScheduler;
    }

    public async Task Handle(MeetingAttendeeAddedIntegrationEvent notification, CancellationToken cancellationToken)
    {
        if (notification.FeeValue.HasValue)
        {
            await _commandsScheduler.EnqueueAsync(new CreateMeetingPaymentCommand(
                Guid.NewGuid(),
                new PayerId(notification.AttendeeId), 
                new MeetingId(notification.MeetingId),
                notification.FeeValue.Value, 
                notification.FeeCurrency));
        }
    }
}
```

**Comment by jgozner** [comment]
That makes so much sense! Thanks for taking the time to reply and explain that :)
