### ISSUE TITLE
CompanyName.MyMeetings.Modules.Payments.IntegrationTests set to .NET Core 3.1 while rest of solution is on .NET Core 2.2

### ISSUE THREAD

**Issue by VantageKR** [kgrzybek/modular-monolith-with-ddd#41]
Hi,
Project CompanyName.MyMeetings.Modules.Payments.IntegrationTests as title syas, is set to .NET Cor 3.1 while rest of solution is on 2.2, so after setting it to 2.2 solution compiles successfully. Please change so that those of us on VS 2017 can still come along for the awesome ride. Thanks for this extremely detailed, extremely complete reference implementation! Great work and volumes to be learned here, so thank you very much for this project and all the hard work that went into it.

**Comment by kgrzybek** [comment]
Thanks @VantageKR, you are right. It was a mistake because the default version during project creation in VS 2019 is 3.1 and I did not change this. 

However, I migrated the whole solution to 3.1 because it has Long Time Support so it will not work in VS 2017 anymore :(
