### ISSUE TITLE
Steps to Obtaining OAuth 2.0 Token

### ISSUE THREAD

**Issue by 274188A** [kgrzybek/modular-monolith-with-ddd#45]
I'm fairly new to token tech but I have tried to use Postman to send a POST with simply query strings to get an OAuth2 token (below) using the method shown [here](https://www.youtube.com/watch?v=cVg5FwRaRgo&list=WL&index=4).  

I'm seeing this error in postman console log:
>Error: Could not complete OAuth 2.0 token request: {"":""} 

I think I'm missing something - but is there an `endpoint` for doing Auth?  
I have used `/oauth/token` but probably not correct but best guess

[https://localhost:5000/oauth/token/?grant_type=password&username=testMember@mail.com&password=testMemberPass&client_id=ro.client&client_secret=secret](https://localhost:5000/oauth/token/?grant_type=password&username=testMember@mail.com&password=testMemberPass&client_id=ro.client&client_secret=secret)

I'm happy to help write up/clarify some baby steps if needed :-)

**Comment by kgrzybek** [comment]
Hi @274188A 

You should follow the instructions included in README:

https://github.com/kgrzybek/modular-monolith-with-ddd#5-how-to-run

There are detailed description how to obtain the token :)

**Comment by DavudSafarli** [comment]
Hi.
Following the instructions in README, which is taken from
[identityserver docs](https://identityserver4.readthedocs.io/en/aspnetcore1/endpoints/token.html):

```
POST /connect/token HTTP/1.1
Host: localhost:5000
 
grant_type=password
&username=testMember@mail.com
&password=testMemberPass
&client_id=ro.client
&client_secret=secret
```

I keep getting 
```
{
  "error": "invalid_request"
}
```

**Comment by VantageKR** [comment]
I find the simplest way to get the token is with Powershell:

```
$ids_host = "http://localhost:5000"
$connect_token_endpoint = "$ids_host/connect/token"
$response = (curl.exe -d "grant_type=password&username=$login&password=$password&client_id=ro.client&client_secret=secret" $connect_token_endpoint) | Out-String
$json = $response | ConvertFrom-Json
$access_token = $($json.access_token)
```

Hope that helps. I think curl does a POST by default.

**Comment by DavudSafarli** [comment]
Issue for me was incorrect database connection string. After checking logs/fixing connection string, making **Form request** gave the correct response.
If you are using Insomnia for API client:
![image](https://user-images.githubusercontent.com/43086951/84110507-1675db80-aa36-11ea-98fa-49e360cbdd30.png)
