### ISSUE TITLE
Serialized messages contains BackingField with duplicated data

### ISSUE THREAD

**Issue by denis-tsv** [kgrzybek/modular-monolith-with-ddd#47]
PROPERTY_k__BackingField values can be removed, they contains duplicated data

Serialized message example
{
	"MeetingGroupProposalId": "674e153e-a1bf-40ce-aa2e-139bf37cd39a",
	"Name": "test",
	"Description": "test",
	"LocationCity": "test",
	"LocationCountryCode": "tst",
	"ProposalUserId": "4065630e-4a4c-4f01-9142-0bacf6b8c64d",
	"ProposalDate": "2020-03-11T01:08:06.1942544Z",
	"Id": "d2757a04-e929-4ccf-a23b-360abe1f5b93",
	"OccurredOn": "2020-03-11T01:08:15.1182219Z",
	"&lt;MeetingGroupProposalId>k__BackingField": "674e153e-a1bf-40ce-aa2e-139bf37cd39a",
	"&lt;Name>k__BackingField": "test",
	"&lt;Description>k__BackingField": "test",
	"&lt;LocationCity>k__BackingField": "test",
	"&lt;LocationCountryCode>k__BackingField": "tst",
	"&lt;ProposalUserId>k__BackingField": "4065630e-4a4c-4f01-9142-0bacf6b8c64d",
	"&lt;ProposalDate>k__BackingField": "2020-03-11T01:08:06.1942544Z"
}

**Comment by kgrzybek** [comment]
Resolved, thanks for the issue!
