### ISSUE TITLE
Accept of MeetingGroupProposal not works

### ISSUE THREAD

**Issue by denis-tsv** [kgrzybek/modular-monolith-with-ddd#49]
When meeting group proposal accepted then created MeetingGroup with MeetingGroupMember where MemberId is MeetingGroup creator Id. But not created new record in table meetings.Members.
And SendMeetingGroupCreatedEmailCommandHandler failed because it tried to find member by creator Id in Members but not MeetingGroupMembers table. 
And we have the same problem with SendMeetingGroupCreatedEmailCommandHandler - it failed every time it executed in infinite loop.
So I think it is possible to avoid the infinite loop using try/catch and Attempts field for internal command. Also it is possible to add relations between tables in database, so it will be impossible to insert new row in table MeetingGroupMembers before inserting corresponding row in table Members 

BTW, why do you decide to use Guid as a primary key type instead of int?

**Comment by kgrzybek** [comment]
It was a problem with InitializeDatabase.sql script. User was added using script, but Member in meetings. Members not. I fixed this. This is another reason to be very careful during making changes directly on the database - you can bypass the system rules and it will crash 😈 

The main reason for using GUID is that it is generated by the application itself. The integer must be generated by another component (like a database) to provide uniqueness and this causes a lot of different problems (especially during DDD implementation). If you can - use GUID.
