### ISSUE TITLE
Visual Studio users must use 2019

### ISSUE THREAD

**Issue by SamWalkerRxSense** [kgrzybek/modular-monolith-with-ddd#58]
Thanks for the great example.  

This is not an issue with the project itself, but I just wanted to share to Visual Studio users that 2019 is required.  .Net Core 3.1 is not supported in previous versions.  Maybe this note will prevent a little grief for someone else.

I was stuck on this way to too long, before noticing VS 2017 warning me that ".NET Core 3.1 is not supported in this version".

This presents as "User context not available" during authorization.

**Comment by kgrzybek** [comment]
Good idea @SamWalkerRxSense, I added note to technology section:
https://github.com/kgrzybek/modular-monolith-with-ddd/commit/a1182424258b967ae6e90499fff063d7d4257162

**Comment by VantageKR** [comment]
Sorry @SamWalkerRxSense! But I must admit it got me too, although only for 2 projects back when I started looking at this code.
Note that the whole solution was .NET Core 2.2, with only two of the test projects on 3.1, but then it was all upgraded to 3.1 for all projects, sadly.
I got a version where it was all 2.2 still, and that seems to work fine for the moment, so you can checkout that version if you like.
.NET Core 3.1 is LTS, and that is the reasoning behind the upgrade.
