### ISSUE TITLE
Why *Request classes are in modules? 

### ISSUE THREAD

**Issue by wmekal** [kgrzybek/modular-monolith-with-ddd#60]
Hi Kamil,

Thank you for your work. It's a food for thinking :). 

I'm analyzing it once again and I would be thankful for explaining one thing - described shortly in subject.

Why *Request classes are in module and not by the controllers?
E.g. `ChangeMeetingMainAttributesRequest`, `AddMeetingAttendeeCommandRequest`, etc.

**Comment by kgrzybek** [comment]
It was a mistake - some request classes were misplaced :). Fixed.

**Comment by wmekal** [comment]
Ok. Thanks.
