### ISSUE TITLE
OutboxMessage in BuildingBlocks has an unused Parameter in its Constructor

### ISSUE THREAD

**Issue by kacey90** [kgrzybek/modular-monolith-with-ddd#67]
The `DomainEventsDispatcher.cs` creates an `OutboxMessage` object (line 73) and passes in the `domainEventNotification.Id` which is not used because the Id in `OutboxMessage.cs` is assigned `Guid.NewGuid();`.

**Comment by kgrzybek** [comment]
Thanks @kacey90 for the issue. Additionally, I found the bug that inbox message id was not the same as outbox message id. Solved as well.
