### ISSUE TITLE
Notification duplicates domainEvents properties

### ISSUE THREAD

**Issue by Lobosque** [kgrzybek/modular-monolith-with-ddd#76]
Hi, I wonder why the definitions of Notifications (classes that inherit from `DomainNotificationBase<>`)
duplicates the properties from the domainEvent.
Why is this needed since the DomainEvent itself is a `DomainNotificationBase` property?

Take `MeetingAttendeeAddedNotification` as an example. It has two handlers:

* `MeetingAttendeeAddedNotificationHandler` uses `notification.AttendeeId`.
* `MeetingAttendeeAddedPublishEventNotificationHandler` uses `notification.DomainEvent.AttendeeId`.

In this case what is the reason not to define `MeetingAttendeeAddedNotification` without any property except those inherited from parent?

**Comment by kgrzybek** [comment]
Hi @Lobosque ,

You are right - it does not make any sense this duplication. Additional properties should be removed. Domain Event has everything. 

It was an idea some time ago to keep only properties that are required without the whole Domain Event object, but this is not required from my experience.

**Comment by Lobosque** [comment]
@kgrzybek I will submit a PR to remove the Notification properties in the next few days.
The `Notification` will then act just as an envelope to the `DomainEvent` so the application module knows it should be broadcasted.
