### ISSUE TITLE
No CI checks while pull request 

### ISSUE THREAD

**Issue by SzymonSmykala** [kgrzybek/modular-monolith-with-ddd#81]
I can see that there are no checks during PR's
![Screenshot 2020-07-05 at 20 08 51](https://user-images.githubusercontent.com/12577111/86539260-59bf4f00-befb-11ea-9ec6-7a892702112a.png)

Also, there is a Azure pipeline created, but it was never run: 
https://dev.azure.com/kgr0189/kgr/_build/latest?definitionId=1&branchName=master

Consider building and running tests during Pull Requests. This is the first step to CI/CD process.

**Comment by kgrzybek** [comment]
Hi @SzymonSmykala 

Definitely agree! I did the pipeline configuration some time ago but later it disappeared, I think it is something with my account. I will investigate this.

**Comment by kgrzybek** [comment]
GitHub Actions pipeline configured in 4ae525b13a7ed26d1b1893a0e7c06e14384fe75b
