### ISSUE TITLE
Raw SQL statements in Application

### ISSUE THREAD

**Issue by CoffeeParser** [kgrzybek/modular-monolith-with-ddd#94]
Thanks for the showcase application.
I think the QueryHandlers (Application layer) should be implemented in the Infrastructure layer, because the implementation uses raw SQL statements, which is a persistence concern.

Moving the QueryHandlers to infrastructure would result in a back reference to the DTOs of the application layer resulting again in a circular dependency between application and infrastructure layers.

I guess the clean solution would be moving the SQL statements into the infrastructure layer and return custom Readmodels that would be converted to dtos inside the QueryHandlers.

**Comment by MarkGravestock** [comment]
Agree with all the comments that this is a well thought out non-trivial application.

I found these 2 justifications/explanations for the current approach (from kgrzybek) as I also had the same thoughts about where the infrastructural concerns should reside.

- https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/docs/architecture-decision-log/0009-use-2-layered-architectural-style-for-reads.md

- From another sample http://www.kamilgrzybek.com/design/simple-cqrs-implementation-with-raw-sql-and-ddd/

There is a similar question in the [discussion](https://disqus.com/home/discussion/kamil-grzybek/simple_cqrs_implementation_with_raw_sql_and_ddd/)

> 'Nice work in between. Im in the decision making step of deciding using CQRS or Repository for queries as they are a bit more complex. I know this is a sample so bear with me. I see you used Dapper in the Application layer. Shouldn't that be an infrastructure concern as with the other repo accessing EF as the Application layer has to handle persistent concerns or this is just a personal decision?'

The answers given is 

> 
> 'Application layer responsibility is an orchestration of the use case. When you have CQRS applied, your Read Model is optimized for reads and simple, so you don't need another layer of abstraction. Only thing to do is get data, nothing else. There is no business logic. You don't need abstract database, because your Read Model is database. You are even not able to write unit test for it.
> 
> On the other hand, speaking about Write Model, if it is Domain Model you want to abstract from database and persistence. You want do that because on write side you have business logic and rules which should be isolated from infrastructure (for example to test this logic).
> 
> You write about "complex reads" - this could be a sign of leaking business logic to queries. It is good to think about it and maybe do some precalculation or aggregation on write side and read side will be less complete'

**Comment by CoffeeParser** [comment]
Thanks for looking up the information. Closing issue.
