### ISSUE TITLE
Possible DDD Rule Violation

### ISSUE THREAD

**Issue by AdemCatamak** [kgrzybek/modular-monolith-with-ddd#99]
Hi @kgrzybek ,

It is a nice work where you applied many best practices and design patterns. There is a lot of information that can be learned through this study. Thank you for your effort. There is a situation that makes me think when I examine your work. In your study, "CompanyName.MyMeetings.BuildingBlocks.Domain" project is designed as a domain project in which common features are written as far as I understand. This project has a dependency on the 3rd party library called "MediatR". I recall a rule that states "domain project should not contain any 3rd party dependencies" in projects developed according to DDD. Does this mean there is a part in your work where one of DDD rules is violated? Since your project is a good example of DDD implementation, I wanted to ask such a question, thinking that there might be a situation that I do not know at the implementation level.

Have a good day

**Comment by ardalis** [comment]
Software design is about tradeoffs. The domain project has to have *some* dependencies, on the underlying framework, for instance, and perhaps on a SharedKernel (in DDD). Dependencies that bring along infrastructure dependencies, like databases, cloud services, files, etc. should pretty strictly be avoided. Those that are pure code, like MediatR, pose less of a problem. It's not unusual to depend on useful pure code packages, like MediatR, for common patterns in the Core/Domain project. My $.02; curious to hear from @kgrzybek as well.

**Comment by AdemCatamak** [comment]
Hi,

@ardalis  and @kgrzybek, thank you for your explanations.

I think we agree at this point: _ideally_, there should be no dependencies in the domain project. Since the dependency on the MediatR library does not reduce the quality of the software and it is easier to use in this way, we allow it to be in the domain project.
